version: '3' 

services: 

  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    env_file: .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=${TRANSMISSION_USER} #optional
      - PASS=${TRANSMISSION_PASS} #optional
      #- WHITELIST=iplist #optional
      #- HOST_WHITELIST=dnsnane list #optional
    volumes:
      - ./MediaServer/transmission/Downloads:/downloads
      - ./MediaServer/transmission/config:/config
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  plex:
    image: linuxserver/plex
    env_file: .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - VERSION=docker
    volumes:
      - ./MediaServer/plex/config:/config
      - ./MediaServer/plex/Peliculas:/peliculas
      - ./MediaServer/plex/Musica:/musica
      - ./MediaServer/plex/Series:/series
    network_mode: host
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    env_file: .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true #optional
    volumes:
      - ./MediaServer/jacket/config:/config
      - ./MediaServer/jacket/download:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - ./MediaServer/sonarr/config:/config
      - ./MediaServer/transmission/Downloads:/downloads
    env_file: .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}